# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "otelcol:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
  clickhouse: 
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4
    database: otel
    ttl_days: 3
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

connectors:
  spanmetrics:
    namespace: traces.spanmetrics
    aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"
    metrics_flush_interval: 5s
    exemplars:
      enabled: true
    histogram:
      unit: ms


processors:
  batch:
    timeout: 5s
    send_batch_size: 100000
  servicegraph:
    metrics_exporter: clickhouse
    dimensions: [cluster, namespace] # Additional dimensions (labels) to be added to the metrics extracted from the resource and span attributes   
    cache_loop: 2m # the time to cleans the cache periodically
    store_expiration_loop: 10s # the time to expire old entries from the store periodically.
    virtual_node_peer_attributes:
      - db.name
      - rpc.service
  metricstransform:
    transforms:
      - include: "traces.spanmetrics.duration"
        action: "update"
        new_name: "traces.spanmetrics.latency"
      - include: "traces.spanmetrics.calls"
        action: "update"
        new_name: "traces.spanmetrics.calls.total"
  probabilistic_sampler:
    sampling_percentage: 50

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,servicegraph]
      exporters: [otlp, logging, spanmetrics, clickhouse]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [metricstransform, batch]
      exporters: [prometheus, logging, clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, clickhouse]